name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd lws-front
          npm install

      - name: Build and tag Docker image for Development
        run: |
          docker build -t jonasrsribeiro/lw-frontend -f Dockerfile.dev .
          docker tag jonasrsribeiro/lw-frontend:latest jonasrsribeiro/lw-frontend:develop

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u jonasrsribeiro --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push jonasrsribeiro/lw-frontend:latest
          docker push jonasrsribeiro/lw-frontend:develop