name: CI

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd lws-front
          npm install

      - name: Create Pull Request
        if: success() && github.ref == 'refs/heads/staging'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GHUB_TOKEN }}
          commit-message: "Merge de staging para prod"
          branch: "prod"
          title: "PR Automatico: Merge de staging para prod"
          body: "Pull request automático de staging para prod."
          labels: "automated,merge"
          reviewers: "jonasrsribeiro"